### ISSUE TITLE
non-fully qualified domains not handled by insecure registry list

### ISSUE THREAD

**Issue by bparees** [containers/buildah#1049]
my insecure registries list includes:
`docker-registry.default.svc.cluster.local:5000`

my image was located at `docker-registry.default.svc.cluster:5000` which, within the context buildah was running in, is resolved to `docker-registry.default.svc.cluster.local` due to the search paths in /etc/resolv.conf.

I would have expected buildah to resolve `docker-registry.default.svc.cluster` to `docker-registry.default.svc.cluster.local` and treat it as insecure, but it did not:

```
Registry for "docker-registry.default.svc.cluster:5000/openshift/ruby:latest" is not present in the registries configuration, assuming it is secure.
```

**Comment by rhatdan** [comment]
@nalind @mtrmac PTAL

**Comment by mtrmac** [comment]
This is the only way it can work (and the way it works in Docker as well, AFAICS):

When making a request though the HTTP stack, we provide an URL, and there is no opportunity to inspect or change how the HTTP stack is interpreting the host name. So, the c/image code never sees the …`.local` host name.

We also _must not_ make a separate DNS resolution call, make a secure/insecure determination based on its results, and then make a separate HTTP call which does its own DNS resolution, because an attacker could provide different DNS responses for both cases (e.g. when asking to connect to TLS-protected `redhat.io`, the attacker could provide a CNAME to your insecure registry the first time, and an IP address of the attacker’s fake version of `redhat.io` the second time, and that would defeat the TLS protection of `redhat.io`.) So, it is fundamentally insecure to do anything else than a straight text match (and, as a consequence, it is fundamentally insecure to match IP addresses or IP address ranges against user-provided hostnames, although Docker does implement that).

As an additional difficulty, it is probably fairly easy to ask the resolver for a “canonical name” of the input, but that would not allow us to determine the difference between a `search` option in `/etc/resolv.conf` (which is, probably, trusted) and a CNAME entry in unsigned DNS (which is definitely not). So, to implement this, c/image would have to specifically understand the `resolv.conf` search mechanism. Sure, it’s “just” code, but hard-coding semantics of `resolv.conf` so many layers higher looks pretty unattractive to me.

**Comment by bparees** [comment]
ok
