### ISSUE TITLE
01-intro.1.md: "--release 26" in dnf install example fails

### ISSUE THREAD

**Issue by rpjday** [containers/buildah#1471]
I am assuming that it is because I am running on Fedora 30 that this command referring to "--release 26" fails:

`# dnf install --installroot $scratchmnt --release 26 bash coreutils --setopt install_weak_deps=false -y`

with:

```
Fedora Modular 26 - x86_64                                       41 kB/s |  50 kB     00:01    
Failed to synchronize cache for repo 'fedora-modular'
Error: Failed to synchronize cache for repo 'fedora-modular'
```

Is there a way to not lock the example to a version?

**Comment by rpjday** [comment]
Hang on, I removed all images and containers and tried again from scratch with "--release 30", but the result was that the original storage was still there and so failed again the same way. Is that expected? How does one rid oneself of storage to make sure there are no remnants from earlier left lying around? Can someone confirm proper operation of this example?

**Comment by TomSweeneyRedHat** [comment]
Just adding a [link](https://github.com/containers/buildah/blob/master/docs/tutorials/01-intro.md) to the tutorial in question.

**Comment by TomSweeneyRedHat** [comment]
@rpjday it's been a while since I've played with this tutorial, so I just ran through it from the start. 
I'm not a huge heavy dnf guy, but I believe the `--release` (actually should be `--releasever`) is required.  As we've specified `--installroot`, dnf will look into $scratchmnt to find the release version if `--releasever` is not specified, that's why it's failing when not supplied.

I'm not completely sure why it's failing  at 26 and 27 though.  This command is working for me though at 28, 29 and 30:
```
dnf install --installroot $scratchmnt --release 30 bash coreutils --setopt install_weak_deps=false
```

The storage if you're going between the two locations should be OK.  When root storage should be in `/var/lib/containers/storage` and as rootless in `~/.config/containers/mount.conf`.  If things are still wonky,  [`buildah unshare`](https://github.com/containers/buildah/blob/master/docs/buildah-unshare.md) will probably help.

@ipbabble or @rhatdan do you know if fedora-modular only supports some number of prior versions?

**Comment by rhatdan** [comment]
I don't know, but the tuturial should definitely be moved to 29.  Also we should add the cache flags to put the cache onto the host and not in the container.

**Comment by TomSweeneyRedHat** [comment]
I'm going to close this as I believe #1479 addresses this.  @rpjday if you disagree, please reopen or create a new issue as you feel best.
