### ISSUE TITLE
Please add installation instructions for Cygwin (Windows), or help get buildah put into the Cygwin packages (setup-x64.exe)

### ISSUE THREAD

**Issue by devlocalca** [containers/buildah#1696]
**Description**
I would like to ask that installation instructions be added on how to install buildah on Cygwin.

buildah has a close relationship with Redhat (Cygwin is owned by Redhat I believe), how can I help get buildah put into the package list, so that I can install using the cygwin installer?  

Same goes with Podman.  I just want to click, have it install, from the looks of packages available there, it looks like they don't discriminate at all, as to what can be put in there, and I believe this is important.

**Comment by rhatdan** [comment]
Buildah and Podman will not work natively on Windows, They are tools that require running linux processes.  There is effort to make Podman run on WSL going on, as well as podman-remote support for Windows, which should allow us to run podman commands natively on a Windows box and have them communicate with Podman running in a VM.

Let's continue the conversation over in https://github.com/containers/libpod/issues/3288 and watching podman-remote development.

I am going to close this issue, since I think we already have your needs covered in other issues.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan this would be a great addition to a "nice to have, looking for contributors" list.    I must admit, I'm an old cygwin fan, so would love to see something implemented there.  I don't have the background or time to do so though.
