### ISSUE TITLE
Provide metadata to indicate version of tools used to create a container

### ISSUE THREAD

**Issue by debarshiray** [containers/buildah#1864]
**Description**

Sometimes when debugging it's useful to know the version of Podman that was used to create a container. eg., a situation where a container that was created with an old version of Podman now fails to start with a newer version.

It would nice if this information was exposed somewhere. It could be via `inspect` or something in `/run/.containerenv` or something else.

**Comment by rhatdan** [comment]
The logical case for this would be in annotations or labels, I would guess.  Putting info into /run/.containerenv is not a bad idea either.

**Comment by caiges** [comment]
Annotations or labels feel like the right place for this (on commit), labels maybe being a bit more visible to end-users. `/run/.containerenv` would work too but I believe that would also require a change to Podman since it'll create an empty `/run/.containerenv` and we could add its version there as well.

**Comment by rhatdan** [comment]
I often have a hard time understanding the difference between Annotations and Labels.

**Comment by caiges** [comment]
My interpretation is that they're functionally similar but different in terms of expectations and location. In the general sense, annotations feel more structured and expected whereas labels are more arbitrary. For instance, I would classify an image caption as an annotation because it's expected (in presence and content) but if the author were to affix an arbitrary piece of text diagonally across one corner of the image to illustrate something, that is more of a label. Technically, they're both labels and I might just be trying to find a hole to put the peg into.

The [spec](https://github.com/opencontainers/image-spec/blob/master/annotations.md) includes the more structured and expected labels that could live in the manifest for the image or the configuration of the image. It also says the data could be arbitrary as well so there's that.

For this issue, I think `/run/.containerenv` or as a label in the configuration is more accessible for the use-case of determining which version of buildah built the image as manifest tooling isn't quite there yet. The podman code for `.containerenv` is similar so the change there would be pretty straightforward -- something like `BUILDAH_VERSION=1.2.3-dev`.

**Comment by rhatdan** [comment]
So you want the container to be able to determine who built the image, as opposed to the user of the image knowing what built it?
Please generate a PR, since I don't think we are against it.  WDYT @vrothberg @mtrmac @nalind

**Comment by mtrmac** [comment]
> Annotations or labels feel like the right place for this (on commit), labels maybe being a bit more visible to end-users. `/run/.containerenv` would work too but I believe that would also require a change to Podman since it'll create an empty `/run/.containerenv` and we could add its version there as well.

If the version number is supposed to work for debugging and workarounds, it should be as close to the top level of the object as possible (i.e. in this case, probably, the image config (manifests are not preserved on `docker pull`)).

Suppose we somehow massively screw up and widely-deployed Buildah X.Y.Z creates incorrectly-formatted layers: if the version number is in the config, a consumer will be able to read it and just the layer reading process; if the version number is inside a layer, it can’t be read. (Sure, this is very unlikely to happen without anyone noticing, and it would also be possible to screw up the config to be unreadable. Just illustrating the general principle.)

As a general intuition, I’m not too thrilled about inserting files that the user didn’t explicitly ask for into the container, but that’s more or less a weak aesthetic opinion.

> So you want the container to be able to determine who built the image, as opposed to the user of the image knowing what built it?

Was that actually requested? I can’t really see the purpose of that. If an image is broken, sure, it’s good to have a version number, and that version number will be used by the user that is figuring out the cause from _outside_ the container. I can’t quite see how the inside of a container should ever care about the version number of the surrounding environment — that really borders on the container escaping its containment and sticking its nose into things it shouldn’t be concerned with.

**Comment by vrothberg** [comment]
I sounds reasonable to me add metadata that describes which tool in which version built the image. There is [a set of pre-defined annotations](https://github.com/opencontainers/image-spec/blob/master/annotations.md#pre-defined-annotation-keys) in the OCI image spec already and I think that the metadata could be added there (e.g., `org.opencontainers.image.builder.name` and `org.opencontainers.image.builder.version`).

Pulling in @vbatts: Vincent, what do you think about the request and where we could add that?

**Comment by vbatts** [comment]
The request is two things: `LABELS` or `annotations` to the portable container image; exposed information to the running container instance.

As for the exposed information, that has been a debated issue for a while. I'm not going to push that topic.

As for the label/annotation, like @vrothberg said, there are _some_ predefined ones. The challenge when a request like this comes up, is that having a `$key` that suits everyone is not as easy since the `$value` is just a string. So each tool that influenced the build of the container can add _its_ own reverse-dns-key, but there is not a described pattern to determine "What are _all_ the tools used, and their versions?". Thankfully the `$key` is just a text string, so you can set it to what ever you like. But it would be a convention that you yourself would have to embrace.

Bonus history, there was a time we discussed (I pushed for) the `$key` to be something like the OID used in SNMP or x.509 v3 extensions. https://en.wikipedia.org/wiki/Object_identifier
The neat thing there is that you may have a prefix that is just for say tool information, then a slot for the vendor, then the remaining suffixes determine for say name, url, version, etc.
It would make detecting this kind of information easier, at the expense of looking cryptic. Some argued the same could be accomplished with reverse-dns, but again, it would be a convention that folks would have to embrace.

**Comment by rhatdan** [comment]
Well this Issue seems to have never led to any thing in the upstream.  What should we do with it?  Should we implement a buildah/podman specific change?

**Comment by vrothberg** [comment]
Yes. I think it wasn't implemented due to a lack of time and urgency.

**Comment by debarshiray** [comment]
It would still be nice to know have this, though.

**Comment by nalind** [comment]
#1917 did part of this, for building using the `buildah commit` command.  If we're talking about having podman version info show up in the `podman inspect` output for a container, that's not something we can fix here.

**Comment by rhatdan** [comment]
I believe we have completed this, reopen if I am mistaken.
