### ISSUE TITLE
Minor document issues and hurdles

### ISSUE THREAD

**Issue by benjamin-bergia** [containers/buildah#1895]
**Description**
Following my comment on #1469, I thought I could share some of the pain points I had during my first few days using buildah and the stuff that in my opinion could be added or put forward in the doc.

To give a bit of context, some of our projects are running on travis free offering and we are slowly moving to drone-ci on kubernetes. I have been looking around for a simple and reliable way to build images on kubernetes in unprivileged containers. I currently do so with a simple wrapper around buildah for drone. 

***Images***
From the get go, the situation with the docker image wasn't really clear. I initially started with 
[buildah/buildah](https://hub.docker.com/r/buildah/buildah). After reading [this nice article](https://developers.redhat.com/blog/2019/08/14/best-practices-for-running-buildah-in-a-container) I moved to [buildah/stable](quay.io/buildah/stable). I think in my case it does make sense to use the image from quay.io since I only need a minimal buildah image but this image was unknown to me before the article.

***Build/Tag/Push***
Coming from docker, I was used to the build/tag/push process and I automatically started by running `buildah bud`, `buildah tag`, `buildah push`. I later found out that `push` could push different image names/tags than the local one and even later found that `buildah bud -t` could use a destination to push the image directly to a registry without `tag` or `push`. Unfortunately, the [doc](https://github.com/containers/buildah/blob/master/docs/buildah-bud.md) on this is not that clear:
>--tag, -t imageName
>
>Specifies the name which will be assigned to the resulting image if the build process completes successfully. If imageName does not include a registry name, the registry name localhost will be prepended to the image name.

***Where did the images go?***
During my phase of running `bud` and `push` I had the weird issue where I could locally run `buildah bud` copy the imageId and then `buildah push` the imageId to a specific registry. Unfortunate when running in my kubernetes pod I would get this weird situation:
- run `buildah bud`
- run `buildah image` which would return nothing (or an empty list if you prefer)
- run `buildah push` the imageId which would tell me that the imageid doesn't exist.
When using the `--iidfile` to pass the id from `bud` to `push` I would get an error saying that base64 or hexa tag cannot be used.

***Caching***
So that's where I am at right now. After some research I found the `--layers` switch.
Unfortunately CI tools like drone create fresh pods for each build and my expectation was that buildah would for each layer try to find it on the registry. It looks to me like it's not the case and I don't really know at this point how I can speed up my builds in this situation.

Sorry for the the messy formatting but I hope this will help with your current work on the doc.

**Comment by TomSweeneyRedHat** [comment]
This is awesome @benjamin-bergia .  Thanks so much for posting this and for the pointers to the pain points that you encountered.  Hopefully we can clean those up.

**Comment by pierreozoux** [comment]
I think you have to improve documentation.

First the website. As a new user, I search directly the "QuickStart" section, here the closest I found was a "tutorial", not that far ok.
I didn't find how to build Dockerfiles easily. I'd be you, I'd switch the OCI to Dockerfile. I think more people want to build Dockerfiles, we are used to that.

And then, it just didn't work on my mac, frustration started. I looked at issues, and saw that I was not alone.
Then, I spent 2 hours to try to make it work on a classic kuebadm/ubuntu/gitlab runner setup.
I expected to be able to make it happen in 10min. 2 hours after, still no luck.

Once I figured out I had to use the quay image, I could start.

I got this error when running in privileged mode:
```
process exited with error: fork/exec /bin/sh: no such file or directorysubprocess exited with status 1
```
Using an older version didn't help.

Before using the priviledged mode, I got this error:
```
permission denied
level=error msg="exit status 1"
```

All I wanted to do is build a Dockerfile, rootless on my mac, or on a classic kubernetes cluster, without configuring anything. I really though that buildah was for this. Maybe I didn't understand?

Then, I remembered that google had one too, kaniko. It took me 5 minutes to make it work.

As an advice, I'd put on the front page that it is still in beta, so that new users can expect that it will not be that easy to get up and running.

I hope this feedback helps!

**Comment by pierreozoux** [comment]
I guess that this project works perfectly on OpenShift.
Maybe a compatibility matrix would help a lot to manage users expectations.

**Comment by TomSweeneyRedHat** [comment]
@pierreozoux I've created https://github.com/containers/buildah/pull/1930 which I think will address the majority of your concerns.  If you think I can add further to that to help with your concerns, please let me know.

'All I wanted to do is build a Dockerfile, rootless on my mac, or on a classic kubernetes cluster, without configuring anything. I really though that buildah was for this. Maybe I didn't understand?'

That was definitely a bit of a hole in our tutorial that I hope my recent changes clarified.  You can't run Buildah (or Podman) in as a 'rootless user' out of the box.  The administrator of the system has to do a little bit of configuration beforehand.  I've added a section to the tutorial with a pointer to the page that lists that necessary configuration for a rootless user.  I did not yet put together a "Quick Start" page, but I think that's a good thought and I'm letting that bubble in my brain for a bit and hope to create one soon.

**Comment by TomSweeneyRedHat** [comment]
@benjamin-bergia forgot to add, your thoughts are up next on my hit list.  Thanks again for those.

**Comment by rhatdan** [comment]
Since the tuturial was updated 9 months ago, and no update on this issue, I am closing. If I mistaken please reopen.
