### ISSUE TITLE
ADD to symlink tar file messes up destination directory

### ISSUE THREAD

**Issue by sophonet** [containers/buildah#2102]
**Description**

If a Dockerfile contains a line ADD tarball.tar.gz DSTFOLDER and tarball.tar.gz is a symlink (e.g. tarball_latest.tar.gz), DSTFOLDER incorrectly gets augmented with tarball.tar.gz.

**Steps to reproduce the issue:**
```
mkdir tarroot
touch tarroot/empty
tar cvfz tarball.tar.gz tarroot --owner=0 --group=0
ln -s tarball.tar.gz tarball_latest.tar.gz

Dockerfile:
FROM centos:7
WORKDIR /
ADD tarball_latest.tar.gz

podman build -t tartst .

podman run -ti --rm tartst /bin/bash
ls -lR /ta*
```
**Describe the results you received:**

Root in container lists (among other entries)

```
/tarball_latest.tar.gz/tarroot/empty
```

**Describe the results you expected:**

```
/tarroot/empty
```

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah/unknown,now 1.12.0-3 amd64
```

**Output of `buildah version`:**

```
Version:         1.12.0
Go Version:      go1.10.1
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:
image Version:   5.0.0
Git Commit:
Built:           Thu Jan 16 15:29:51 2020
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:            1.7.0
RemoteAPI Version:  1
Go Version:         go1.10.1
OS/Arch:            linux/amd64
```

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Output of `uname -a`:**

```
Linux system 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary read-write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional read-only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers (currently overlay, zfs, vfs, btrfs)
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by TomSweeneyRedHat** [comment]
@sophonet Thanks for the issue.  We'd a number of issues with symlinks that we've fixed, I thought we'd gotten this too.   Will take a look.

**Comment by TomSweeneyRedHat** [comment]
@sophonet Are you getting any errors when you run the `podman build` command?  If so could you paste the error?  Also could you run with debug logging please?  `podman --log-level=debug build -t tartst .`

**Comment by TomSweeneyRedHat** [comment]
@sophonet in your Dockerfile you have:

`ADD tar`ball_latest.tar.gz`

That failed for me until I changed it to:

`ADD tarball_latest.tar.gz /`

This worked for me using upstream.  Can you verify that you ADD command has a target please?

**Comment by sophonet** [comment]
@TomSweeneyRedHat indeed, there was a typo in the problem description. I hade set the target as you have suggested before noticing the problem:

```
[root@08e5076972d8 /]# ls -lR /ta*
/tarball_latest.tar.gz:
total 4
drwxrwxr-x 2 root root 4096 Jan 23 07:19 tarroot

/tarball_latest.tar.gz/tarroot:
total 0
-rw-rw-r-- 1 root root 0 Jan 23 07:19 empty
```
Building runs without giving me any errors (at least without the debug flag). With the debug flag turned on, I see the attached output.

[podmanbuildlog.txt](https://github.com/containers/buildah/files/4101792/podmanbuildlog.txt)

The interesting lines are:

```
DEBU[0000] Parsed Step: {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:add Args:[tarball_latest.tar.gz /] Flags:[] Attrs:map[] Message:ADD tarball_latest.tar.gz / Original:ADD tarball_latest.tar.gz /}
STEP 3: ADD tarball_latest.tar.gz /
DEBU[0000] extracting contents[0] of "/home/sophonet/podmanlink/tarball.tar.gz" into "/home/sophonet/containers/storage/overlay/33a8222c466d9ec47251d4ae5db8ab5ef662165987599a1ce1c5f0826323072d/merged"
DEBU[0000] parsed reference into "[overlay@/home/sophonet/containers/storage+/run/user/1111:overlay.ignore_chown_errors=true,overlay.mount_program=/usr/local/bin/fuse-overlayfs]@68cbd03d41d6310b107969ffd6d6ebf006129fab4bca3cdb21b8b8e65334fbc3"
DEBU[0000] exporting opaque data as blob "sha256:68cbd03d41d6310b107969ffd6d6ebf006129fab4bca3cdb21b8b8e65334fbc3"
```

which do not look suspicious.

By looking at the changes in buildah/util.go, the relevant code for adding tarballs in copyFileWithTar() has not changed for 8 months, so I am puzzled why this should work upstream...

**Comment by TomSweeneyRedHat** [comment]
@sophonet thanks for the clarifications.  I wasn't sure if you were seeing an error during the command execution or incorrect behavior after the command ran "successfully".  Correct me if I'm wrong, but I think what you seeing is no error emitted from the `buildah bud` command when it runs, but when looking in the container the files aren't placed where you'd expect them to be.

I've just tried your test again with Docker and Buildah.  I first created a '/tom' directory with a `verifyme.txt` file under it.  I tared that up into `tarball.tar.gz` and then created a link to it called `tarball-latest.tar.gz`.

When I ran your Dockerfile with Docker, it created `/tom` directory under `/` with a `verifyme.txt` file under it.  However, when I ran your Dockerfile with Buildah, it created a `tarball_latest.tar.gz` directory under `/` and under there lived `./tom/verifyme.txt`.  

If I change the Dockerfile to use the tarball directly rather than the link, then Buildah appropriately puts stuff into `/tom/verifyme.txt` in the container.

So the issue I'm seeing is if a link to the tarball is specified in the Dockerfile, then it inserts an extra directory (`/tarball_latest.tar.gz`) when it should not.  That smells very much like an issue with how Buildah is handling symlinks, I'll dive into that.

If by chance this is not the problem that you spotted, please let me know.

**Comment by sophonet** [comment]
Indeed the issue you describe is the one I have observed and which I have tried to capture in my initial problem description.

I was suspecting the lines [in buildah/util.go's copyFileWithTar that do a symlink check](https://github.com/containers/buildah/blob/6e277a2d8f4af200197d02a126f92351c2b15e21/util.go#L171) but I am not a tar/go expert.

**Comment by TomSweeneyRedHat** [comment]
@sophonet, thanks for the confirmation, glad I'm on the same page as you.  I think I've a fix for the issue, but set it aside last night after the eyelids won their battle.  Need to test more today.  But I think the issue is higher up the chain than what you've spotted.  I think the issue is [here](https://github.com/containers/buildah/blob/master/imagebuildah/stage_executor.go#L456)

I think we need to drop the Join() and just pass in srcNameSecure there.  With the code as is, the destination is getting set to `/root/tarball_latest.tar.gz` when I think it should instead be set to `tarbal.tar.gz`.  It works for this particular test, but I need to try some other setups with links that point down lower in the directory structure before calling it found/fixed.
