### ISSUE TITLE
Installation of buildah on UBI8 based container

### ISSUE THREAD

**Issue by vrushaliinamdar** [containers/buildah#2128]
**Description**
Getting following error while installing buildah 1.14.0 on UBI8 container. Could you please guide me on this?

Installing dependencies:

Running transaction check
Error: transaction check vs depsolve:
**rpmlib(PayloadIsZstd) <= 5.4.18-1 is needed by crun-0.11-1.fc32.ppc64le**
To diagnose the problem, try running: 'rpm -Va --nofiles --nodigest'.
You probably have corrupted RPMDB, running 'rpm --rebuilddb' might fix the issue.
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.

Thanks,
Vrushali

**Comment by TomSweeneyRedHat** [comment]
@vrushaliinamdar can you tell us the steps you took to setup the UBI8 container please?  Also how you went about installing Buildah on the container?

**Comment by nalind** [comment]
`rpmlib()` dependencies are used to mark features that a package requires from RPM itself.  In this case it looks like the `crun` package's contents (or "payload") are compressed using the zstd library, but the version of RPM in the container predates that feature, so it wouldn't know how to decompress it, and you get an error instead of a failure further on in the process.

To check whether or not your version of RPM supports this, you can run `rpm --showrc` and look through its list of "Features supported by rpmlib".

Based on the [Fedora feature description](https://fedoraproject.org/wiki/Changes/Switch_RPMs_to_zstd_compression), it looks like the payload in packages built for Fedora 31 or later is compressed using zstd, while packages built for older releases used xz, a different format.  You appear to be attempting to install a `crun` package that was built for the Fedora 32 development tree, so it makes sense that it would have been built using zstd compression.

Based on [this discussion](https://stackoverflow.com/questions/9292243/rpmbuild-change-compression-format/10255406), it appears that using a Fedora 32 system to rebuild source packages using either `rpmbuild` or `mock` with `--define '_binary_payload w9.xzdio' --define '_source_payload w9.xzdio' ` flags would produce binary packages with payload compressed using xz.

There are other points of divergence between the version of Fedora that was originally used as the base for RHEL 8 and current versions of Fedora, so you'll still need to contend with those, but that's how I'd try to tackle the compression part.

**Comment by vrushaliinamdar** [comment]
@TomSweeneyRedHat I am doing this as part of [codewind-pfe](https://github.com/eclipse/codewind/tree/master/src/pfe) component. 

@nalind Thanks. I will try your suggestions

**Comment by rhatdan** [comment]
@vrushaliinamdar I take it you have gotten past this.  CLosing.
