### ISSUE TITLE
need solution to deal with command which need both single and double quote combined with pipe or output redirection

### ISSUE THREAD

**Issue by ttys3** [containers/buildah#2136]
**Description**

I've  already read [Troubleshooting Guide](https://github.com/containers/buildah/blob/master/troubleshooting.md#3-buildah-run-command-fails-with-pipe-or-output-redirection) about the solution to "buildah run command fails with pipe or output redirection"

take this as an example:  https://github.com/docker-library/php/blob/703a3d0a4e4c149bfd62fc3e7b71645f9496b178/7.4/alpine3.11/fpm/Dockerfile#L174

```bash
runDeps="$( \
	scanelf --needed --nobanner --format '%n#p' --recursive /usr/local \
		| tr ',' '\n' \
		| sort -u \
		| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
)"; \
apk add --no-cache $runDeps
```

 it's hard to do with buildah run when the command need use both single and double quote,
because `sh -c` itself need single quote

any suggestions please ?  how to `buildah run` the command above conveniently?
 
**Steps to reproduce the issue:**
no need to

**Describe the results you received:**

**Describe the results you expected:**

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.12.0-2.fc31.x86_64
```

**Output of `buildah version`:**

```
Version:         1.12.0
Go Version:      go1.13.5
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.0.0
Git Commit:      
Built:           Thu Jan  1 08:00:00 1970
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
Fedora release 31 (Thirty One)
```

**Output of `uname -a`:**

```
Linux localhost.localdomain 5.4.15-200.fc31.x86_64 #1 SMP Tue Jan 28 09:08:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by TomSweeneyRedHat** [comment]
@ttys3 I've tried playing with it a bunch this afternoon evening and have run out of steam.  I know what's happening, but haven't found the adjustment yet.  The problem is the `$(scanelf ...)` isn't running inside of the container, but within the host.  If you use the `--` option, I thought it would then do everything within the container, but again it's still expanding and running everything in the parens.  For instance:

```
# buildah run tom  --  runDeps=$(scanelf)
-bash: scanelf: command not found
```
Where as this works:

```
buildah run tom -- /bin/sh -c scanelf
* Scan ELF binaries for stuff
{lots of help info removed for brevity}
```

So my thinking is you could potentially do something like:
```
 buildah run tom -- /bin/sh -c scanelf --needed --nobanner --format '%n#p' --recursive /usr/local | tr ',' '\n' | sort -u | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }'
```

and possibly capture that output and feed that to `apk add` command?

```
bulidah copy tom tom.txt /
buildah run tom -- /bin/sh -c apk add --no-cache  /tom.txt
## or
buildah run tom -- /bin/sh -c apk add --no-cache $(cat tom.txt)
```

But that's not working, doesn't look like apk know what to do with the file, it returns apk help.  I'm not an apk heavy, any thoughts?

**Comment by rhatdan** [comment]
This is not an issue with buildah, but is a scripting issue.  I would advise you to put your advanced scripting into a shell script and add it to the container image.
