### ISSUE TITLE
RFE: Add --ignore/-i support to the build command (Original title: Podman's dockerignore build context support?)

### ISSUE THREAD

**Issue by dm17** [containers/buildah#2761]
As described in this issue: https://github.com/moby/moby/issues/12886
Does Podman support this same functionality?
Thanks!

**Comment by TomSweeneyRedHat** [comment]
@dm17 We don't support that from what I can see, but I'll let @QiWang19 correct me if I'm mistaken.
I'm going to change the title of this issue and make it a request to add the functionality.  It looks like it would be doable.

For a quick thumbnail sketch, this is requesting adding the `--ignore/-i` option to the build command which would allow the user to specify a particular `.dockerignore` file to use rather than the default.

**Comment by dm17** [comment]
Thanks! And moreover, I'm investigating how build contexts work when there are multiple Dockerfiles and potentially multiple docker-compose.yml files within a repository - and how one builds them using docker-compose (podman-compose) build.

**Comment by rhatdan** [comment]
According the the Moby link above.  You would like us to use Dockerfile.dockerignore and Containerfile.dockerignore

IE if I do a buildah bud -f /PATHTO/foobar /tmp, then we should grab
/PATHTO/foobar.dockerignore if it exists, otherwise we would look for /tmp/.dockerignore.

buildah bud and podman build has `--ignorefile` now.

**Comment by rhatdan** [comment]
This is fixed.
