### ISSUE TITLE
podman-remote build, with missing ARG: warning displayed on server, not client

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#3214]
In window 1 (actual separate window, don't just background it in the same window as the client):
```console
# podman system service --timeout=0
```
In window 2:
```console
# cat Containerfile
FROM alpine
ARG FOO
# ../bin/podman-remote build .
[normal output, but:]
```
back to window 1 (server):
```
WARN[0041] missing "FOO" build argument. Try adding "--build-arg FOO=<VALUE>" to the command line
```
That diagnostic does not do any good on the server end. It should be displayed on the client. (In fact, there is a buildah-bud test that expects this, and is failing when tested under podman).

**Comment by nalind** [comment]
Hmm, actually it might be cleaner for the service to use `logrus.SetOutput()` to point logrus's standard logger to one stream or another.  That way we wouldn't have a library (buildah) messing with global settings for another library (logrus) in ways that a package that consumes them both (e.g., podman) might not be expecting.

**Comment by nalind** [comment]
Yeah, if you want logrus messages from _everywhere_ (including libraries that buildah also depends on) logged somewhere other than the global defaults, I'm thinking `logrus.SetOutput()` is necessary and your only viable option.

**Comment by rhatdan** [comment]
This is going to be a very difficult problem in a client server mode.  Since logrus is shared across the process,  We can't modify it's settings since we could have two or more remote image builds going on at the same time.  I think we will need to wire in the buildoptions down the stack and stop using logrus or at least also write the messages to the buildahopts.Err.  This is a lot more then just this one warn, since there are lots of calls to logrus, inside of run_linux.go.

**Comment by nalind** [comment]
And in the common, image, and storage libraries.
