### ISSUE TITLE
Include microdnf and qemu-user-static in stable container image

### ISSUE THREAD

**Issue by anthr76** [containers/buildah#3301]
Considering multi-arch is gaining more popularity and buildah is now well available in CI pipelines what are the maintainers thoughts in adding microdnf and qemu-user-static to the stable container package?

1. qemu-user-static is useful to reduce on multi-arch build times instead of waiting for dnf to update it's repos and install
2. microdnf is useful to install other packages the user might want without the bloat of yum or dnf. If size is a concern maybe we remove DNF/YUM?

**Comment by nalind** [comment]
qemu-user-static works by configuring the kernel's binfmt_misc feature.  It does this by setting values in /proc/sys/fs/binfmt_misc, either when the package is first installed, or when the system is subsequently rebooted, to configure the kernel invoke the right emulators based on information encoded in the headers of binaries that have been compiled for non-native architectures.  The emulator binaries aren't going to be in a stable location if they're distributed as part of a container image rather than as an OS-level package, and in most cases we're not going to be allowed to make those changes to the host's kernel's run-time configuration.  Based on that, I don't know that including the package in the container images is going to be sufficient.

I don't really have an opinion on swapping between microdnf and dnf.  I think we currently just let the container images inherit whichever one their base images include.  Perhaps other maintainers more familiar with our plans around the container images can chime in.

**Comment by anthr76** [comment]
The qemu-user-static bit makes sense. I wonder how that shakes out in something like GitLab CI. I do also see this interesting project https://github.com/multiarch/qemu-user-static

**Comment by nalind** [comment]
Based on what I'm reading at https://hub.docker.com/r/multiarch/qemu-user-static/, the "register" image registers its emulators with the kernel, and can be run again to but it needs to be run with --privileged in order to do so.

One thing I forgot about the "F" flag (https://www.kernel.org/doc/html/latest/admin-guide/binfmt-misc.html), which Fedora's package for qemu-user-static uses, is that the kernel opens the binary immediately, so my concern about the location of the binary being unstable looks unfounded.

**Comment by anthr76** [comment]
Looks like your analysis has been correct. Trying to get multi-arch builds on GitLab's CI has been a... challenge.

Can't really shim in qemu-user-static on GitLab's shared runners since you start with the buildah container. Even though it's running as a privallaged docker container `dnf install -y qemu-user-static` isn't enough.. (https://gitlab.com/kutara/container-images/test/-/jobs/1353629457#L135)

Also having another fair share of troubles running an unprivileged build in Kubernetes (https://github.com/containers/buildah/issues/3053#issuecomment-859610721) I can at least guarantee a node will have emulation software. Though without unprivileged a build will not succeeded.

**Comment by rhatdan** [comment]
@nalind @anthr76 What is going on with this issue?  Should we close it or is there something Buildah can do to fix it?

**Comment by anthr76** [comment]
Considering qemu-user-static won't work the way I expected we can close this.. Having microdnf in the image is nice though as sometimes you may need to pull images while in CI. Incase anyone comes along to the issue looking to build multi-arch images on gitlab SaaS CI this is how I did it https://gitlab.com/kutara/gitlab-ci-templates/-/blob/master/jobs/build/base.yml#L54-77

**Comment by fengxsong** [comment]
Building multi-arch images in container/Pod MUST run in privilege mode and execute script `test -f /proc/sys/fs/binfmt_misc/register || mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc` manually first.
