### ISSUE TITLE
Unclear terminology: image vs container

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/buildah#3305]
My understanding is, that image is a read-only template, whereas container is a read-write thing. Always.  Thus if something is a container, then both `podman` and `buildah` consider it as container.  When something is an image, then both `podman` and `buildah` consider it as image.

I call `buildah from --name abc scratch`.  `buildah images` and `podman images` have the same output and they do not consider the new thing to be an image.

`podman containers ls` does not show anything, so the new thing is from podman perspective not a container.

`buildah containers` however returns the new thing, so that the new thing is a container (with CONTAINER NAME=abc , IMAGE NAME=scratch , BUILDER=*=yes IMAGE ID = "").

So the new thing is a container from buildah perspective, but is not a container from podman perspective.  This is utelry confusing.

Please elaborate on the difference between container in terms of buildah and containers in terms of podman.

**Comment by rhatdan** [comment]
Let's look at this in multiple layers.

Podman, Buildah and CRI-O, Skopeo have the same concept of images.
Skopeo has no concept of Containers.

Images are defined in containers/image and can be stored in different types of storage.  Registries, Docker Archives, OCI Archives, Docker-daemon as well as containers/storage.  When dealing with images most people think of those as stored in containers/storage. (Or those stored in container registries).  For the rest of this description we will concentrate on container/storage.

Container/storage also provides it's concept of a `storage container`.  Basically a storage container is intermediate storage content that has not been committed yet.  Think of this as files on disk and some json describing the content.  

Podman, Buildah and CRI-O all use "storage containers".  All three container engines also have additional data specific to the container engines.

Buildah Container include additional content referring to the different commands that make up the Containerfile.

For example Workingdir, Env Variables, and other data used to build a container image.

Podman also has it's own datastore of data related to a Podman container.  There is far more data stored in the Podman database then in the Buildah database. You could think of the Buildah database to be a subset of the Podman database.  

CRI-O again has its own datastore to describe it's containers.

All three tools have evolved differently and have different ideas and requirements for "their own containers".  For example CRI-O containers have evolved with a reliance on a single daemon controlling them, and the concentration is on performance and the ability to share thousands of responses to the Kubernets CRI per second.  Since it knows it is the only one dealing with the datastore, it can take advantage of storing it in memory.  Podman on the other hand needs to deal with
multiple uses of its containers at the same time, so it needs to rely more on file system locking, and making sure hundreds of Podman executables can reliably share the same datastore. We have always talked about eventually merging the two together, but over time, we feel that the risk/benefit is hard to justify the merge.

Buildah was also developed as an independent tool and the maintainers have pushed back on taking on the unneeded weight and complexity of the Podman datastore, for little to no additional benefit. Also
how would Podman handle a container created with the `buildah from scratch` command? We would still need to treat these partially created containers differently.

The latest versions of Podman can now list the "storage containers" available on the system.

```
$ podman ps -a --external | grep buildah
578edf9430ee  scratch                                   buildah               13 days ago   storage                          working-container
```
You can mount and unmount these containers

```
# podman mount working-container
/home/dwalsh/.local/share/containers/storage/overlay/a4f596beaabdc78efc7694a67d690097e327aa12bbc59165d011e62b646e93c0/merged
# podman unmount working-container
working-container
```
You can also remove these containers
```
$ podman rm working-container
working-container
```
But you can also  create these containers using `podman build`, of course these are temporary only during the build.

But since they don't have the same data as a podman container, they can not be started/stopped, and podman ps does not show them when they are running.

Podman also has similar ability to work with CRI-O Containers.

**Comment by rhatdan** [comment]
This looks like a new blog.
