### ISSUE TITLE
1.21.1 and 1.21.2 missing in quay.io repository

### ISSUE THREAD

**Issue by rostrovsky** [containers/buildah#3365]
**Description**
Latest versions of buildah: `1.21.1` and `1.21.2` are not available on quay.io. We would like to check if we can use those because `1.21.0` doesn't pass vulnerabilities check in our company, while `latest` is ok. Unfortunately we can't import `latest` images into our internal registry, so we'd like to check fixed versions.

**Steps to reproduce the issue:**
1. Open https://quay.io/repository/buildah/stable?tab=tags
2. Search for tag `1.21`

Only `1.21.0` is present

**Comment by rhatdan** [comment]
@cevich @TomSweeneyRedHat PTAL

**Comment by cevich** [comment]
So the way this works today is, after image build we actually execute the tool (i.e. buildah) to query the version number.  When the reported version is new (tag doesn't exist in quay), we push it up then never ever touch it again (which may be why vulnerability scanning fails).  Since buildah in the container comes from a package (in the stable and testing images), bumping the version number actually means first releasing a new package (and going through the long list of related steps).

@rostrovsky since you're importing these into an internal registry anyway, is it conceivable you could periodically grab the stable:latest image from quay, but internally tag it with the complete buildah version?

It's possible [something here is broken](https://github.com/containers/buildah/actions/workflows/multi-arch-build.yaml), which I will investigate shortly...

**Comment by cevich** [comment]
...done.  The automation for 'stable' is working as designed, though I did note that 'testing' is bringing in version `1.21.2`.  So as that version moves through the process, it will eventually show up in stable.

@lsm5 is anything abnormal blocking 1.21.2 moving out of F34 updates-testing (I'm just double-checking)?

**Comment by cevich** [comment]
>periodically grab the stable:latest image

Clarification: This won't get you a newer buildah version, but it may get you past the vulnerability scanning since the rest of the image's packages are continuously updated (daily).

**Comment by rostrovsky** [comment]
Unfortunately I work in tightly controlled environment and can't import `stable:latest` 😢 
`1.21.0` has only one vulnerability that prevents us from import: https://github.com/frenzymadness/CVE-2021-3572

**Comment by cevich** [comment]
> Unfortunately I work in tightly controlled environment

Understood.  The tagged images are driven by the available/released buildah package.  I see we have 1.21.2 in the updates-testing repo. but that has no hard-connection to pip updates (or anything else for that matter, unless it's an explicit dependency).

@rostrovsky can you check if `quay.io/buildah/testing:latest` has an acceptable version of `pip`? Better yet, can you can check to see that it passes all your validations?

Reason I ask is, it's entirely possible that a buildah 1.21.2 package goes from updates-testing into updates, triggers a new container image that still has an old version of pip (or something else that fails your checks).  Then, because of how we never again touch the version-tagged images, you're stuck :confounded: 

@rhatdan & @TomSweeneyRedHat I know we've been over and over this before...are you ***sure*** we can't change stance, and continuously push the version tagged images daily (esp. so we pick up security updates)?  In my mind, the version tag represents the buildah interface, not the rest of the container, so this /should/ be okay exception in my mind.

**Comment by rhatdan** [comment]
I am not against this.  I to agree that this is the version of Buildah not the version of the image.

**Comment by rostrovsky** [comment]
Hi, just scanned `quay.io/buildah/testing:latest` (image digest: `f7c27ddf5efdd1b45006166ce590046b73aae2c9162fd100f0aa74d2f58fb531`).

Unfortunately it still has the same vulnerability.

**Comment by cevich** [comment]
> Unfortunately it still has the same vulnerability.

Thanks for checking, that's helpful to know, so my fear is a real possibility then.  The buildah package could update, get an image tagged, and still not update `pip` (or whatever has a security problem next).  Worse, since we never update the tagged images, those problems will persist no matter the buildah version.

One potential complication with continuously updating the tagged images is, it will force users to download new images every day, even if there are no package changes (since the timestamp is different) :frowning: Off-hand, what we could do is track two things when deciding to build: The buildah version, and a hash of the package listing (includes version numbers).  Then, only push updated version-tagged images if the package-list hash changes.

Note: This doesn't at all address actual packages getting updated due to security issues, that workflow needs to move forward on it's own.  The proposed change would simply mean we actually present those updates over time, despite the buildah version not changing.

**Comment by cevich** [comment]
@rostrovsky please give another poke at `quay.io/buildah/stable:v1.21.0`  My PR w/ updated workflow just merged.  If we're lucky, your CVE fix also made it in (I didn't check).  If not, you may need to hunt down the specific package maintainer(s) and see what's what. On our-end, we'll now build & pushing the latest version-tagged image on a daily basis.  So soon as any fix gets into the main repos, we'll pick it up at most 1-day later.

Shortly I'll make the same workflow change to podman and skpeo as well.

**Comment by rostrovsky** [comment]
Hi, just to confirm: `quay.io/buildah/stable@sha256:d825ce3e14bbff0a4f05c2168fb786e7ba324607a26edd71f37e63bfe19f42e2` does not have any substantial vulnerabilities. We'll be able to import it. Thanks! 👍
