### ISSUE TITLE
--rusage-logfile flag missing from man pages

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#3432]
https://github.com/containers/buildah/pull/3267 introduces the rusage-logfile option, but there's no man page for that.  @dcermak as you created the option, could you please update the man page?

**Comment by dcermak** [comment]
I did not add any docs about that option, because `--log-rusage` itself is not documented and judging from https://github.com/containers/buildah/pull/3267#issuecomment-850814893 I thought that it was intentional that this option is not documented in the man page. I can document it though, if these two options should become visible to users.

**Comment by rhatdan** [comment]
It is a hidden option, not something we want to directly support, so I don't want it documented in the man page.
