### ISSUE TITLE
IBM Cloud account is not active

### ISSUE THREAD

**Issue by soukainakhalkhouli** [containers/buildah#3962]
Hello team ,
While pushing images into ICR, i'm getting this error:
error copying layers and metadata from "containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage]us.icr.io/cicd-tekton/external-cms-backend:latest" to "docker://us.icr.io/cicd-tekton/external-cms-backend:latest": Error trying to reuse blob sha256:11936051f93baf5a4fb090a8fa0999309b8173556f7826598e235e8a82127bce at destination: unable to retrieve auth token: invalid username/password: unauthorized: The login credentials are not valid, or your IBM Cloud account is not active.

Any idea about that ?
<img width="1440" alt="Screen Shot 2022-05-04 at 17 15 14" src="https://user-images.githubusercontent.com/71095703/166742865-aff67edf-a04a-4fc2-9eac-1e0ac929f712.png">

**Comment by Dexus** [comment]
are you logged-in? `buildah login us.icr.io`
tried with oci transport?

**Comment by soukainakhalkhouli** [comment]
How can  i do that, i'm using buildah with tekton if you have any idea ?

**Comment by soukainakhalkhouli** [comment]
@Dexus 
I'm getting this error STEP-PUSH

+ buildah login us.icr.io
Username: error getting username and password: error reading username: EOF

**Comment by Dexus** [comment]
login like on docker.
If this not work, I'm not the right person to help you.

**Comment by flouthoc** [comment]
@soukainakhalkhouli I think @Dexus is correct you would need to populate any one of these inside tekton build container `${XDG_CONFIG_HOME}/containers/auth.json (usually ~/.config/containers/auth.json), $HOME/.docker/config.json, $HOME/.dockercfg.`  

But tekton can populate `~/.docker/config.json` out of the box from `kubernetes secrets` see : https://tekton.dev/vault/pipelines-v0.16.3/auth/#configuring-authentication-for-docker

I am closing this issue since this looks like more of a tekton issue rather than buildah but please feel free to continue the discussion or re-open if you think something is wrong with buildah here.

**Comment by soukainakhalkhouli** [comment]
@flouthoc ,
Thank you for your response, i'm using tekton for CI/CD  in openshift , i don't have any idea if i should create a secret and apply it after or what exactly i should do .
Regards

**Comment by flouthoc** [comment]
@soukainakhalkhouli I think `secrets` and `serviceaccount` are just kubernetes construct so it should be available in openshift as well. So you just need to associate created `serviceaccount` with Tekton's `PipelineRun` or `TaskRun` as stated here: https://tekton.dev/vault/pipelines-v0.16.3/auth/#configuring-basic-auth-authentication-for-docker

**[Not Recommended]** If you don't want to use `secrets` you can just populate `~/.docker/config.json` in your `Tekton Task` manually in `script` section in one of your `steps`. **[Not Recommended]**

Still I think `tekton` or `openshift/tekton` forums  might be the best place to discuss this.
