### ISSUE TITLE
A few hiccups with go get github.com/containers/buildah

### ISSUE THREAD

**Issue by Alanthur** [containers/buildah#4035]
I follow the tutorial https://github.com/containers/buildah/blob/main/docs/tutorials/04-include-in-your-build-tool.md
Adding Buildah as a Go dependency "as-is" fails with errors:

>  pkg-config --cflags  -- devmapper
pkg-config: exec: "pkg-config": executable file not found in $PATH
 github.com/proglottis/gpgme
/home/go/pkg/mod/github.com/proglottis/gpgme@v0.1.1/data.go:4:11: fatal error: gpgme.h: No such file or directory
    4 | // #include <gpgme.h>
      |           ^~~~~~~~~
compilation terminated.
 github.com/containers/storage/drivers/btrfs
/home/go/pkg/mod/github.com/containers/storage@v1.40.2/drivers/btrfs/btrfs.go:9:10: fatal error: btrfs/ioctl.h: No such file or directory
    9 | #include <btrfs/ioctl.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.

I do not know how fix it.
My os : Ubuntu 20.04.2 LTS
My go : go version go1.17.8 linux/amd64

**Comment by flouthoc** [comment]
Hi @Alanthur,

I think you are missing `libgpgme-dev` and `btrfs-progs` so `sudo apt-get install btrfs-progs libgpgme-dev libgpg-error-dev` should fix it. But I think you might get hit with further missing deps in such case refer to list of needed deps here https://podman.io/getting-started/installation#build-and-run-dependencies

I am closing this issue since this looks like your system is missing some deps but please feel free to continue discussion below.

**Comment by Alanthur** [comment]
@[flouthoc](https://github.com/flouthoc)
thanks for you help.
