### ISSUE TITLE
Add a flag to "skip unneeded stages from multi-stages"

### ISSUE THREAD

**Issue by SaurabhAhuja1983** [containers/buildah#4243]
**Description**

Following issue is fixed in version 1.27.1 and it skips the unwanted images to improve performance.
https://github.com/containers/buildah/issues/2469
I would like to move this feature behind a flag, 
something like
--skip-unused-stage=false
as it's breaking the backward functionality and skipping the target images that were added deliberately for kubernetes manifests. 

**Steps to reproduce the issue:**
1. buildah bud --target backend
2.
3.

**Describe the results you received:**
STEP 1: FROM alpine AS frontend_builder
STEP 2: RUN touch frontend
STEP 3: FROM alpine AS frontend
STEP 4: COPY --from=frontend_builder /frontend .
STEP 5: FROM alpine AS backend_builder
STEP 6: RUN touch backend
STEP 7: FROM alpine AS backend
STEP 8: COPY --from=backend_builder /backend .

**Describe the results you expected:**
STEP 1: FROM alpine AS backend_builder
STEP 2: RUN touch backend
STEP 3: FROM alpine AS backend
STEP 4: COPY --from=backend_builder /backend .

**Output of `rpm -q buildah` or `apt list buildah`:**

```
```

**Output of `buildah version`:**

```
Version 1.27.1
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Output of `uname -a`:**

```
Linux agent-797ff4d976-7z567 5.10.102-flatcar #1 SMP Wed Mar 2 19:40:13 -00 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
[storage]
# Default Storage Driver, Must be set for proper operation.
driver = "overlay"

[storage.options.overlay]
# Path to an helper program to use for mounting the file system instead of mounting it
# directly.
mount_program = "/usr/local/bin/fuse-overlayfs"
```

**Comment by flouthoc** [comment]
Thanks for creating the issue, this was discussed somewhere in past but we were unable to realize any actual use-case, but sure adding a flag for this seems like a good idea. 

One small question why does your kubernetes manifest need stages which are not actually used ? Is it for a test ?

**Comment by nalind** [comment]
FWIW, the use case in OpenShift is that build job spec can include an optional `postCommit` field which specifies a command to be be run in the just-built image as a confidence check, before it's pushed to a registry.  If the command fails, the build job is considered to have failed even if the image was itself built successfully.

This offers the ability to run commands that create state that should only be created when the image is run the first time (think log files, or sparse files).  If those commands were run using a RUN instruction tacked on at the end of the main image build, explicit cleanup would be needed in order to avoid polluting the resulting image.

We did come up with a workaround that should have minimal side-effects that we can use in OpenShift builds, but over time, my thinking's been coming around to just disabling the optimization there as well, so that the workaround won't be necessary.

**Comment by mtrmac** [comment]
(A drive-by comment by someone who doesn’t really understand the codebase:)

The “disable optimization” approach seems to me rather imprecise; it is not telling Buildah what the user actually _wants_.

- If the goal is to create multiple images, shouldn’t Buildah be _told_ about that, so that it can still optimize out other unused stages? E.g. allow multiple values to `buildah build --target`, but still run the optimization. (That would possibly make the `Containerfile` a bit more `Makefile`-like … I don’t know how I feel about that.)
- If the goal is to run tests, shouldn’t Buildah similarly be told _not_ to tag the resulting image? Or even to automatically delete all intermediate images?

**Comment by flouthoc** [comment]
I agree `--target` can be used to control which stages need to be used. Although  not sure if `--target` can fulfill the use case of Openshift job spec which executes `RUN` just for sanity check and not adds anything to the `target` stage.

I see that kaniko implements a similar flag https://github.com/GoogleContainerTools/kaniko#flag---skip-unused-stages so i guess buildah should be fine implementing it , where flag defaults to `true` right ?

**Comment by rhatdan** [comment]
SGTM
