### ISSUE TITLE
[FEATURE] push support hosts option

### ISSUE THREAD

**Issue by yylt** [containers/buildah#4992]
**Description**
In our environment, there are many registry use same domain, they locate in differnet kuberetes cluster
could support `--hosts` option for push sub command? like build same option

like this:
```
buildah push --add-host registry.example.com:2.2.2.2  docker://registry.example.com/foo:bar
```

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `rpm -q buildah` or `apt list buildah`:**

```
(paste your output here)
```

**Output of `buildah version`:**

```
$ buildah version
Version:         1.23.1
Go Version:      go1.17
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
(paste your output here)
```

**Output of `uname -a`:**

```
(paste your output here)
```

**Output of `cat /etc/containers/storage.conf`:**

```
(paste your output here)
```

**Comment by rhatdan** [comment]
@vrothberg @giuseppe @Luap99 @mtrmac WDYT?

This basically switches out a dns name for a specific IP.

**Comment by mtrmac** [comment]
> there are many registry use same domain,

- I feel I must question the validity of that design. That just calls for extreme confusion when debugging. Of course it’s something that can be done… but we should not prioritize impractical designs when adding features.
- How does `push --add-host registry.example.com:2.2.2.2  docker://registry.example.com/foo:bar` really differ from `push docker://2.2.2.2/foo:bar`? Is it that the registry refuses to respond if the `Host:` header does not contain the expected host name? That… just reaffirms my impression that the design is incorrect in the first place. Give the registry a real, unique, host name visible outside the cluster (or expose it using a k8s Ingress or something similar), and use _standard_ tools, instead of using an unusual design that requires _every single tool_ to add a custom option.
- Adding some kinds of redirects via `registries.conf` is anticipated in principle; we only have mirrors on reads, and we probably don’t want a full “mirror” support on push (requiring a push to multiple destinations — what do we do on a partial failure?); but a redirect on push would be easy to add. But then… the default would be _just_ a redirect, where we contact a different host name and send a Host header appropriate for the redirect target (`2.2.2.2` in this case). Adding a way to redirect without changing the Host header … feels extremely niche and not something I think we should prioritize working on.

It’s quite possible I’m missing something about the constraints, or about the situation — but at a first glance, my impression is that this falls _way_ below the line of things we can prioritize, and probabl (?) even below the line of where we should want to accept a PR.

**Comment by yylt** [comment]
In our environment, there are many Kubernetes clusters, and their networks are isolated from each other. Therefore, we have to deploy registry services in each cluster with the same domain. Since external access to the registry service can only be done through ingress, and it use the same domain name. Additionally, since the delivery artifacts are for the entire Kubernetes cluster and often cannot access the internet, this is another reason why we use the same domain name. 

Currently, this can be achieved in the CD pipeline by setting `pod.spec.hostAliases`, but it would be more nice if just   modify the args.

**Comment by Luap99** [comment]
I agree with @mtrmac points, such a design makes no sense to me. Setup an internal dns server or use hosts file (as you are doing right now) seems like the better way instead of patching every network application to support something like that.

**Comment by yylt** [comment]
as discussed.
