### ISSUE TITLE
Global setting for pull trough registry mirror cache

### ISSUE THREAD

**Issue by jonaskello** [containers/buildah#4999]
We are currently using kaniko to build images in gitlab CI. I think there is about 50 projects on or gitlab server that are building images. When docker did rate limiting all the builds quickly hit the limit. Fortunately I found that kaniko can use an env variable to specify a mirror and that gitlab allows for adding varibles that are global to all projects in the gitlab server. So I could simply set `KANIKO_REGISTRY_MIRROR` on the global level and all 50 projects were automatically using the pull trough cache.

Now I want to switch from kaniko to buildah and am looking for the same kind of setting that could easily be globally set. So far I have only found the `registries.conf` [file](https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md). This is very flexible but it is also hard to configure on a global level for a CI server. Having 50 projects manually create this file in their build definitions is not very convient and there will of course be projects that forget this and then the rate limit will be quickly filled.

So, first, I wanted to check if there is some other way to configure this for buildah that is easier to centralize? (I did half a day of googling on this but come up empty :-))

I there is no such config available then I would like propose that as a feature request. For us the simplest way would be if there was a global `BUILDAH_REGISTRY_MIRROR` env var setting but some other way to do it might also work as long as it is possible to globally configure it in the gitlab server.

**Comment by rhatdan** [comment]
@vrothberg @mtrmac PTAL

**Comment by vrothberg** [comment]
Thanks for reaching out, @jonaskello!

Do I understand you correctly that you desire an environment variable `*_MIRROR` which would point to _mirror_ to use when pulling any image?  It's not a variable that would point to a path of a registries.conf file, right?

**Comment by flouthoc** [comment]
I like the idea of setting mirror via env maybe make it `CONTAINERS_REGISTRY_MIRROR` so all `podman`, `buildah` and `skopeo` can use it.

**Comment by mtrmac** [comment]
Would it make sense for Buildah to provide a `buildah required-images Containerfile` command? Or maybe that already exists? I think that could be useful for other UI and dependency analyses, and it would allow auto-generating the required `registries.conf` stanzas, without us having to hard-code any particular naming policy.

---

- How does an environment variable differ from a system-wide config file for your use case?
  - Especially, if the primary concern is `docker.io`, that can be resolved by a single config file setting up a mirror just for that registry, can’t it?
  - Is it just that the specific pipeline mechanism allows globally defining an environment variable, but not a config file?
- Or is the request to have a single mirror that affects _all_ registries, without having to list them? That would require somehow hard-coding a mapping policy for where to look for images on the mirror, and possibly that policy resulting in conflicts (if we strip the host name, `docker.io/nginx/nginx` vs. `quay.io/nginx/nginx`. If we don’t strip the host name, we still need to deal with port number differences, because `:` is not valid in namespaces). Ugh.

- Implementation-wise, I’m not very happy with lower layers like c/image silently changing behavior based on environment variables. But we could have callers opt-in via `pkg/cli/environment`.

**Comment by jonaskello** [comment]
@vrothberg Yes you are correct, the preferred solution would be an env variable pointing directly to a mirror address. Today we have this setting on a global level in our gitlab server so all CI jobs that runs kaniko get this env var without any extra config and thus pulls from that mirror (which is a docker registry setup as pull-trough cache):

```
KANIKO_REGISTRY_MIRROR=registry-mirror.ourcompany.local
```

**Comment by jonaskello** [comment]
> * How does an environment variable differ from a system-wide config file for your use case?

It is not possible to have a system-wide config file since we build in a k8s cluster and every CI build will build on a new host. I think this is true for many CI environments that all jobs don't run on a single host that you can manually configure with extra files.

>   * Especially, if the primary concern is `docker.io`, that can be resolved by a single config file setting up a mirror just for that registry, can’t it?

The primary concern would be any public registry that is rate limited, but I only know of `docker.io` for now.

>   * Is it just that the specific pipeline mechanism allows globally defining an environment variable, but not a config file?

The env variable is the simplest and most efficient solution. I think you can also specify that the key/value should be a file, and then gitlab creates a random temporary file name and the name of the file is stored in an env variable named as the key, and the file contains the contents of value. This however is more complex and runs slower (having to inject the file). But if this is the only way to solve it I think it may be possible if there is an env variable that allows you to point to the path of a registries.conf file.

**Comment by computeralex92** [comment]
We solved this problem by using a internal container image containing Buildah and a registries.conf.

**Comment by rhatdan** [comment]
Is this still an issue, since we have a work around?

**Comment by jonaskello** [comment]
@rhatdan As a workaround you are referring to building your own image instead of using the official one? This works but has some cons:

- You have to maintain a registry where to store this image
- You have to update and rebuild your image for each new buildah version
- You have to make certain all projects/teams on the gitlab instance are actually using your image instead of the official one

If buildah had the same global option as kaniko all of that extra work could be avoided.

**Comment by rhatdan** [comment]
@mtrmac @vrothberg any final thoughts on override via environment variable?

**Comment by mtrmac** [comment]
I don’t like a single global mirror feature; it requires hard-coding a naming policy, and the use cases cited above are a _single_ registry (`docker.io`), so they don’t warrant such a big-hammer approach.

**Comment by rhatdan** [comment]
Ok, I going to close the issue, since we want to be able to handle the general case of multiple registries.
