### ISSUE TITLE
buildah bud --cache-from functionality needed

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#620]
**Description**
`buildah bud --cache-from` is missing and needs to be provided.  This is functionality that Docker has.

#599 is the parent issue for this issue.

**Output of `buildah version`:**

Buildah v0.16

**Comment by rhatdan** [comment]
We don't currently support cache, so this one might take a while.

**Comment by rhatdan** [comment]
Now that we have support for --cache, @umohnani8 Could you add this functionality.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @umohnani8 Is this fixed in buildah?

**Comment by TomSweeneyRedHat** [comment]
It's still a no-op in the code with nothing really happening underneath it other than saying "not supported".

**Comment by rhatdan** [comment]
is it something we could implement?

**Comment by TomSweeneyRedHat** [comment]
I think we could get --cache-from to work for "real", but I've not dived through the code to see if we can for sure.

**Comment by rhatdan** [comment]
@rhatdan Any movement on this one?

**Comment by rhatdan** [comment]
@ashley-cui Could you take a look at this?

**Comment by mfolnovic** [comment]
Parent issue ( #599 ) was closed, so I was wondering if this will be implemented?

This has a huge impact on building images from CI.

Unfortunately this issue is the only reason I prefer Docker in CI (while living with issues Docker has). After implementing this issue, I don't see any reason to not use Buildah in CI.

Otherwise, Buildah is really awesome, nice work!

**Comment by rhatdan** [comment]
Sadly no one has picked up the work on this one yet.
@nalind WDYT?
@TomSweeneyRedHat Do you have time to look into this?
@mfolnovic Any chance you would want to take a stab?

**Comment by mfolnovic** [comment]
@rhatdan with a few pointers, I could try :) :)

**Comment by TeNNoX** [comment]
What exactly do you mean by pointers?
Implementation hints? or functionality-wise?

**Comment by mfolnovic** [comment]
@TeNNoX implementation hints :)

**Comment by haampie** [comment]
Any news on this issue?

**Comment by TomSweeneyRedHat** [comment]
@haampie I'm afraid I've not had time to look into this, I've been chasing other fires and I don't believe anyone else has.

**Comment by rhatdan** [comment]
@sujil02 Would you like to take a look at this?

**Comment by sujil02** [comment]
> @sujil02 Would you like to take a look at this?

Sure. I will give it a shot.

**Comment by haampie** [comment]
Great! Note that docker currently has two different ways in which it supports --cache-from.

The traditional way would be: docker pull img, docker build --cache-from=img

But with buildkit you can do `DOCKER_BUILDKIT=1 docker --cache-from=img --build-arg BUILDKIT_INLINE_CACHE=1` and it will lazily download layers

**Comment by rhatdan** [comment]
@ashley-cui PTAL
@sujil02 I don't believe you are still looking at this?

**Comment by sujil02** [comment]
> @ashley-cui PTAL
> @sujil02 I don't believe you are still looking at this?

Yeah, I am not. I tried going around this a couple of times but could not get far.

**Comment by apollo13** [comment]
I am with @mfolnovic on this one, while `buildah` is usually fast enough it simply cannot beat a cache. Especially for docker files that make clever use of caching by ordering the instructions to utilize the cache as much as possible.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @nalind @ashley-cui @QiWang19 Do we have any action on this?

**Comment by TomSweeneyRedHat** [comment]
@rhatdan way off my radar.

**Comment by apollo13** [comment]
No takers? :D

**Comment by rhatdan** [comment]
Not yet @apollo13 Are you interested in working on it?

**Comment by apollo13** [comment]
Sadly no, my Go knowledge is close to non-existent :(

**Comment by rhatdan** [comment]
@TomSweeneyRedHat PTAL

**Comment by liskin** [comment]
Can we perhaps at least make the `--cache-from` manpage description less confusing? It still reads `… Buildah does not currently support caching so this is a NOOP.` from [the first commit that added it back when there was no caching](https://github.com/containers/buildah/commit/8e77a0c2f7e7806f0cd12e6257d4b77af823d8c5) and it was never updated.

**Comment by rhatdan** [comment]
Please open a PR to clarify.

**Comment by rhatdan** [comment]
@nalind @TomSweeneyRedHat @umohnani8 Now that we have multi-stage builds shouldn't this be fairly easy to add?
@umohnani8 PTAL

**Comment by rhatdan** [comment]
@umohnani8 Any chance you can look at this?

**Comment by rhatdan** [comment]
@umohnani8 Any time for this now?

**Comment by learnitall** [comment]
I'd love to take a crack at it if y'all still need a volunteer. I saw the "Good First Issue" tag and figured this would be a good opportunity to get involved. Would be great for integration in the [redhat buildah github-action](https://github.com/redhat-actions/buildah-build) to speed up GHA workflows.

**Comment by rhatdan** [comment]
GO for it.

**Comment by learnitall** [comment]
Just a quick update: been making some great progress and I think I'll have a working implementation here soon. Going to try to raise a PR by EOW if I can, but we'll see what happens with school.

**Comment by flouthoc** [comment]
@learnitall Thanks just to confirm does your approach involves integrating `buildkit` or is it addon to native buildah.  Asking this as issue has a label `buildkit` so it might automatically solve few more unrelated issues if your solution involves integrating `buildkit` if not then also it is good.

**Comment by learnitall** [comment]
I had originally thought about doing this native, but buildkit integration might be a good idea. I can look into it. My gut tells me that doing buildkit integration might be hard to maintain due to high coupling, but I'm not sure.

After doing some research yesterday though, I realized that the way I was going about it only allows for using an entire image as a cache, rather than being able to break the image down into its individual layers. I don't think buildah has the ability to export cache blobs from the CLI, which will make this more difficult. There's a lot more functionality that buildah needs in order to support the `--cache-from` that docker has

**Comment by learnitall** [comment]
Hm looks like there is support for exporting blob cache to a directory, but it was made hidden: https://github.com/containers/buildah/blob/main/CHANGELOG.md#v16-1-2019-01-18. Anybody have background on this?

**Comment by nalind** [comment]
It's used primarily to avoid having to re-extract and recompress contents of layers that a build inherits from its base image, when the built image is expected to end up being pushed to a different registry than the one that is home to the base image.  There's no logic for pruning the cache, as it was intended for use in builds that happen in containers on clusters, where the builder container is thrown away at the end of a build.

**Comment by learnitall** [comment]
Ah that makes sense, that's a cool use case. I wish that wasn't hidden though, as using blobs seems to be the way that all of this layer caching is done. For instance, I've figured out a way to use pulled images as a cache, however it's all or nothing. I'm not sure how to do caching on a per-usage layer yet and could use some help. It's weird, as `--cache-from` is meant to import a cache but I can't find anything in buildah besides the hidden blob code for actually exporting a cache. 

Here is what I'm thinking the process would be like, but can anyone double check me on this? I know this is a wall of text, but I'm still trying to learn the `containers` go ecosystem and want to make sure I get this right.

Here is what I've done so far:

* Modify the cache-from argument in `pkg/cli/common.go` to be a list of strings in order to support multiple image arguments
* Add a `cacheImages` option to the `buildOptions` to pass the given user arguments to the `Executor`.
* Within the `Executor` before the build begins, parse the given arguments from the user to see if they exist in local storage. Then store the images that exist in an attribute for later use.
* Within the `StageExecutor` while checking for a `cacheID`, look through the given `cacheFrom` images to see if one of them is valid for the image we are building. Validity is checked by doing a history and diffID comparison.

Here is what I'm planning to do next:

* Implement some look-ahead functionality within the `Executor` or `StageExecutor` to determine which cache-images can be used, rather than doing a basic history check which can be really inaccurate.
* Implement the ability to pull cache-from images that don't exist in local storage and the ability to check if a cache-from image is valid during the 'look-ahead' just by reading a manifest, rather than pulling the entire image.

Here is what I need confirmation and direction on:

* Within the `Executor`, after parsing/pulling cache-from images, save the image as a tarball and extract to a temporary directory in order to get access to the image layout, which can then be used to create a `blobCacheReference`.
* Use the `blobCacheReference` to reuse blobs when available, maybe utilizing `image.TryReusingBlob`.
* Cleanup the extracted cache-from images after build is complete
* Give users the ability to specify cache directories and tarballs.

Am I correct in assuming that `blobs` are how inline-layer caching is achieved? The above bullets are the easiest way I can think of adding a quick `--cache-from`. 

I'd have to look through more `buildkit` code to understand how they store cache information in a repository separate from the image, but I think that a change like that, i.e. adding a whole cache-export system into buildah, is out of scope for this issue? And might need to be broken down into smaller chunks?

Also, @flouthoc can you expand on your comment about using buildkit? I think I'm a bit confused. I agree that using `buildkit` could solve some unrelated issues, but isn't `buildah` meant to be a more alternative to `buildkit` and vice-versa, therefore making it counter-productive to use one inside the other? I guess I'm not sure on the lines here, as if there is all this work being doing to implement `buildkit` features into `buildah` natively, then why use `buildkit` for this issue?

Thanks y'all!

**Comment by flouthoc** [comment]
@learnitall oh did my buildkit comment confuse you. If yes that was not my intention my idea of `buildkit` integration was to plug already written code in buildkit as library in buildah. But I think native approach is better as it will keep things simple. Please carry on with your original approach.

**Comment by learnitall** [comment]
Ah ok, thanks for clarifying!

**Comment by rhatdan** [comment]
@learnitall Are you still looking at this?
@flouthoc Could you take a look at this?

**Comment by learnitall** [comment]
Progress has been pretty slow on my end just due to a heavy workload this semester at uni. About a week after my last comment the amount of homework I had per week started to skyrocket. With the semester ending though and the amount of homework I have winding down I should have more time to work on this.

**Comment by rhatdan** [comment]
@learnitall @flouthoc any progress?

**Comment by flouthoc** [comment]
@rhatdan I think @learnitall is still working on this issue. There is no update from my side.

**Comment by learnitall** [comment]
I've been taking a look and this is going to be tricky for me- my understanding of the container's go ecosystem is not very robust. I can continue to try and figure this out, but I'm not very confident in how good/quick I can do this. Might be good for someone with more experience with buildah (i.e. @flouthoc) to take this one over. I saw the 'good first issue' label and thought this would be a simple change, but it's a bit out of my wheelhouse.

The main difficulty I'm facing is that right now there is being able to extract information about an image's layers in order to understand which layers can be used for the cache. In the caching setup that's already in place, all of the cached layers are stored as individual images, but when using the `--cache-from` argument, user's are passing in an image that is collapsed' and made up of multiple layers that may or may not have enough metadata available for caching? Maybe I'm missing something but that's the crux for me right now.

**Comment by rhatdan** [comment]
@flouthoc Please help.

**Comment by flouthoc** [comment]
> The main difficulty I'm facing is that right now there is being able to extract information about an image's layers in order to understand which layers can be used for the cache. In the caching setup that's already in place, all of the cached layers are stored as individual images, but when using the `--cache-from` argument, user's are passing in an image that is collapsed' and made up of multiple layers that may or may not have enough metadata available for caching? Maybe I'm missing something but that's the crux for me right now.

Container images could contain images which are made of multiple layers. Layers could have `digests` and `history`. Mostly `history` should be enough to tell if layer can be used as cache or not. By `metadata` if you mean history , then yes if `layer` is missing history then we cannot use that in `cache`. @nalind Please correct me if i got anything wrong here.

>  @flouthoc) to take this one over.

Sure if you agree then I'd like to take a stab at this. Thank you so much for adding context to this issue.

**Comment by learnitall** [comment]
Ah I see, ok. Thank you for the explanation @flouthoc, please go for taking a stab at it! I'll try to learn as much as I can from your work. Thanks y'all for giving me a chance to work on this, I definitely learned a lot so far but getting some help would be a good way forward.

**Comment by seb2020** [comment]
Hello,

I have found this issue and I am lookink if there is any news about it's resolution ?

Thanks

**Comment by flouthoc** [comment]
Hi @seb2020, thanks for a reminder. I am picking it up. Will update here.

**Comment by etegan** [comment]
Looking forward to following the progress on this issue =)

**Comment by flouthoc** [comment]
@seb2020 @etegan @carej-upstart `Docker`'s `--cache-from` is a bit different from `buildkit`'s `--cache-from` .

1. Docker `--cache-from` does not do lazy pulling of blobs and image needs to be pulled before it can be used as a `cache` source. This is fairly easy to implement.

2. Buildkit's `--cache-from` does lazy pulling of needed layers. But a bit tricky to implement.

Do you guys have any specific priority on `1` or `2` ? I feel we might need to different issue to track this.

**Comment by Korijn** [comment]
For me, I want to be able to leverage cache across builds on CI. I don't really care about how it's implemented/designed. If I could export the build cache and restore that, it would also be super useful.

**Comment by apollo13** [comment]
I that is all you want I can strongly recommend kaniko. It can cache inside the registry itself (and possibly even use a separate cache registry) which makes this kind of things really nice. Like buildah it does not require a running daemon etc…

**Comment by titou10titou10** [comment]
@apollo13 one no-go for me to use kaniko, from the [github readm](https://github.com/GoogleContainerTools/kaniko)

> kaniko is meant to be run as an image: gcr.io/kaniko-project/executor. We do not recommend running the kaniko executor binary in another image, as it might not work.

And it does not (yet) run rootless :[#105](https://github.com/GoogleContainerTools/kaniko/issues/105)
(But this issue is about buildah, not kaniko)
Our use case is to run our CICD pipelines in OpenShift (currently OKD v4.10) from tekton pipelines, and currently running buildah in a tekton ClusterTask is waaaayyy too slow (~5 mins to build an OpenLiberty based image..)

**Comment by Korijn** [comment]
I have tried this but no cache hits, sadly!

I did use `podman` instead of `buildah`, and I didn't specify `--layers` because it's default true according to the help output:

`      --layers                                       cache intermediate layers during build. Use BUILDAH_LAYERS environment variable to override. (default true)`

I should perhaps also note we work exclusively with multi-stage Dockerfiles.

**Comment by carej-upstart** [comment]
> @seb2020 @etegan @carej-upstart `Docker`'s `--cache-from` is a bit different from `buildkit`'s `--cache-from` .
> 
> 1. Docker `--cache-from` does not do lazy pulling of blobs and image needs to be pulled before it can be used as a `cache` source. This is fairly easy to implement.
> 2. Buildkit's `--cache-from` does lazy pulling of needed layers. But a bit tricky to implement.
> 
> Do you guys have any specific priority on `1` or `2` ? I feel we might need to different issue to track this.

I would like `--cache-from` to do something and not silently do nothing. If I have to explicitly pull the image first, as one would with Docker, that's acceptable to me.

**Comment by etegan** [comment]
> @seb2020 @etegan @carej-upstart `Docker`'s `--cache-from` is a bit different from `buildkit`'s `--cache-from` .
> 
> 1. Docker `--cache-from` does not do lazy pulling of blobs and image needs to be pulled before it can be used as a `cache` source. This is fairly easy to implement.
> 2. Buildkit's `--cache-from` does lazy pulling of needed layers. But a bit tricky to implement.
> 
> Do you guys have any specific priority on `1` or `2` ? I feel we might need to different issue to track this.

My use case is that I want to be able to use ansible-bender (uses buildah as a backend) to build images with CI. In this case lazy loading would very much be preferred.

**Comment by mtrmac** [comment]
An implementation design note:

A trivial lazy approach is to just always pull the `--cache-from` image (untagged). Then the existing reuse logic can kick in.

It also seems possible enough to turn `--cache-from` into a `c/image/types.Image`, and to teach the existing cache reuse logic to consider that one extra image as one more candidate, in addition to images that already exist in c/storage. If it matches, we would just pull it, and be done.

A major missing part of both of the above is that that would only trigger reuse on _one_ build step, because each cache lookup only finds images with exactly the expected history (not a prefix). So we would re-do N-1 operations, and then reuse the image for the last operation of the cached image — if the `--cache-from`’s image history is a prefix of the current build instructions. If the `--cache-from`’s image history and the current build instructions diverge, there would be no reuse.

So we need to be able to do a _prefix_ history match, e.g. reuse 3 layers out of a 5-layer `--cache-from` image. The trouble with _that_ is the image only carries a config for the final built image, not for any of the intermediate steps. So with the `--cache-from` image
```Dockerfile
FROM something-common
# (A) A local image eligible for cache matching exists as of this point
ENTRYPOINT entry1
ADD file1
# (B) The --cache-from image and the current build instructions are common up to this point
ENTRYPOINT entry2
ADD file2
# (C) The cache-from image exists at this point
```
we can’t just reuse the `--cache-from` image the way the code is currently doing, by just setting “build outcome = cachedImage.ID”, because that would reuse both the layers and the config from point (C). We need to reuse just the layer from (A)…(B), and separately _independently build_ the config changes from (A)…(B).

That’s definitely possible in principle (and it would be great! It would help layer reuse also in non-`--cache-from` situations), but it seems like a fairly major restructuring of the existing build logic; instead of
- (matching TopLayer, history matching all build instructions to this point) => reuse cache image
it seems that we would need
- (cache image’s TopLayer is somewhere in our history, build instructions to this point match a prefix of cache image history) => reuse layers, manage our own config if necessary.

**Comment by Korijn** [comment]
Maybe I misunderstood something but I thought the compounding problem is that the image you would pull doesn't contain _build cache_ information, so you still wouldn't be able to reuse it unless you also tackle that problem.

**Comment by n1nj4-r4cc00n** [comment]
Hello over there, any news on this one? it would be nice to use the cache for these builds, as mentioned in multiple comments above, this is an important pain point on CI  workloads

**Comment by flouthoc** [comment]
This should be available in the next upcoming release via `--cache-to` and `--cache-from`.
